### ISSUE TITLE
论文里公式(12)

### ISSUE THREAD

**Issue by songyonger** [z-hXu/ReCU#1]
您好，请问公式(12)里 在if|w|=Q(t)，为什么f(w)=1-t呢？我将|w|=Q(t)代入密度函数(1/2b)*(exp(-|w|/b))之后得到的结果是(1-t)/b。如果是因为经过ReCU之后w的密度函数发生了变化，那么f(w)=1-t又是怎么得到的呢？
![图片](https://user-images.githubusercontent.com/46994308/126990509-bc4eded2-e438-443a-8583-ae7323a3a64c.png)

**Comment by z-hXu** [comment]
你好，可以参考一下这个pdf
[reply for eq(12).pdf](https://drive.google.com/file/d/1_SurhEM-0pNh8HiQmdkZuPzBOp3RJKma/view?usp=sharing)

**Comment by songyonger** [comment]
谢谢！
