### ISSUE TITLE
Why weights of intermedium layers are not binary(+1 or -1)?

### ISSUE THREAD

**Issue by kriskrisliu** [z-hXu/ReCU#7]
Thanks for sharing the excellent code! 
I have 2 questions.
(1) When I use torch.load(<model_path>) to access weights of intermedium layers (e.g. layer1.0.conv1.weight), I get a tensor which contains many decimal (e.g. 1.8295e-02, ).   Why are weights not +1 or -1?

(2) The memory size of pre-trained resnet18_1w1a on cifar-10 is 80+MB, while resnet20_1w1a is only 2+MB. What makes 2 models so different in size?

**Comment by z-hXu** [comment]
A1: The weights of pretrained model we provide are actually the proxy weights (full-precision weights before binarization, updated during backpropagation), and you can use a sign function (torch.sign) to convert the proxy weight to binarized weights, which are all +1 or -1.
A2: Resnet-20 is designed for small resolution (32) dataset, such as CIFAR-10 / CIFAR-100, while Resnet-18 is designed for dataset with relatively large resolution (224), such as ImageNet (it is also compatible with CIFAR-10). So Resnet-20 will be more lightweight.
