### ISSUE TITLE
When loading (official) pretrained weights it results in "unexpected kyes in state_dict" (which implies resnet architecture mismatches with pretrained weights)

### ISSUE THREAD

**Issue by kriskrisliu** [z-hXu/ReCU#8]
Thank you for sharing the code!
I have one question when evaluating the pretrained model on cifar-10.
I run "evaluate.sh"(with necessary modification) in <path/to/ReCU/cifar> with pretrained weights(ResNet-18_92.82 and ResNet-18_finetune_93.24 respectively). The execution crashes with errors(Unexpected key(s) in state_dict...) which seems like that the architecture defined in <path/to/ReCU/cifar/models_cifar/resnet2.py> mismatches with pretrained weights.
Do I misunderstand some codes?
In other words, what are general steps to do evaluation with pretrained model(yours) on cifar-10?
Thank you again.

ResNet-18_92.82 and ResNet-18_finetune_93.24 are downloaded from your google-drive.
**Command lines in "evaluate.sh":**
```
DATA_PATH=./dataset/download_cifar10 # checked by training from scratch
best_model_path=/home/ubuntu/github/ReCUnet/ResNet-18_92.82/model_best.pth.tar
python -u main.py \
--gpus 0 \
-e $best_model_path \
--model resnet18_1w1a \
--data_path $DATA_PATH \
--dataset cifar10 \
-bt 128 \
```
**Errors in terminal:**
```
Traceback (most recent call last):
  File "main.py", line 327, in <module>
    main()
  File "main.py", line 86, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/ubuntu/anaconda3/envs/recu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
 Unexpected key(s) in state_dict: "layer2.0.shortcut.0.weight", "layer2.0.shortcut.0.alpha", "layer2.0.shortcut.0.tau", "layer2.0.shortcut.1.weight", "layer2.0.shortcut.1.bias", "layer2.0.shortcut.1.running_mean", "layer2.0.shortcut.1.running_var", "layer2.0.shortcut.1.num_batches_tracked", "layer3.0.shortcut.0.weight", "layer3.0.shortcut.0.alpha", "layer3.0.shortcut.0.tau", "layer3.0.shortcut.1.weight", "layer3.0.shortcut.1.bias", "layer3.0.shortcut.1.running_mean", "layer3.0.shortcut.1.running_var", "layer3.0.shortcut.1.num_batches_tracked", "layer4.0.shortcut.0.weight", "layer4.0.shortcut.0.alpha", "layer4.0.shortcut.0.tau", "layer4.0.shortcut.1.weight", "layer4.0.shortcut.1.bias", "layer4.0.shortcut.1.running_mean", "layer4.0.shortcut.1.running_var", "layer4.0.shortcut.1.num_batches_tracked".
```

**Comment by z-hXu** [comment]
Sorry for the inconvenience! I have optimized the code but forgot to update the pretrained model link. You can simply replace https://github.com/z-hXu/ReCU/blob/master/cifar/models_cifar/resnet2.py#L43-L46 with https://github.com/z-hXu/ReCU/blob/master/cifar/models_cifar/resnet2.py#L70-L73, it should run correctly. 
In the updated code, we remove the convolution in the shortcut and reduce the number of model parameters, while keeping the accuracy almost unchanged.

**Comment by kriskrisliu** [comment]
It works as expected! Awesome！
